version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: clinic-pet-postgres
    environment:
      POSTGRES_DB: clinic_pet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clinic-pet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinicpet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_ENABLE_CSRF: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
